<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MYDUYEN" failures="2" tests="3" name="Calculator Tests" time="0.505" errors="0" timestamp="2024-10-02T11:11:08 ICT">
  <testcase classname="failedPASS.CalculatorTest" name="testAddition" time="0.135"/>
  <testcase classname="failedPASS.CalculatorTest" name="testAdditionFail" time="0.02">
    <failure type="java.lang.AssertionError" message="expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [4]
at failedPASS.CalculatorTest.testAdditionFail(CalculatorTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testAdditionFail -->
  <testcase classname="failedPASS.CalculatorTest" name="testSubtraction" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at failedPASS.CalculatorTest.testSubtraction(CalculatorTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSubtraction -->
</testsuite> <!-- Calculator Tests -->
